language: python

sudo: required

services:
  - docker

branches:
  only:
    - master

env:

before_install:
  - docker version

install:
- pushd ..
- git clone https://github.com/kbase/jars
- docker pull kbase/kb-sdk
- cd ..
- docker run kbase/kb-sdk genscript > kb-sdk
- export KBSDK=$(pwd)/kb-sdk
- chmod a+x $KBSDK
- popd
- $KBSDK version
script:
- $KBSDK validate

after_success:
- coveralls
